import { ALL_BOOKS } from "@/lib/books";

const normalizeAlias = (value: string) =>
  value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "");

const manualAliases: Record<string, string> = {
  genesis: "GEN",
  exodo: "EXO",
  levitico: "LEV",
  numeros: "NUM",
  deuteronomio: "DEU",
  josue: "JOS",
  juizes: "JDG",
  rute: "RUT",
  samuel: "1SA",
  reis: "1KI",
  cronicas: "1CH",
  esdras: "EZR",
  neemias: "NEH",
  ester: "EST",
  jo: "JOB",
  joao: "JHN",
  salmos: "PSA",
  proverbios: "PRO",
  eclesiastes: "ECC",
  canticos: "SNG",
  cantico: "SNG",
  isaias: "ISA",
  jeremias: "JER",
  lamentacoes: "LAM",
  ezequiel: "EZK",
  daniel: "DAN",
  oseias: "HOS",
  obadias: "OBA",
  miqueias: "MIC",
  habacuque: "HAB",
  sofonias: "ZEP",
  zacarias: "ZEC",
  malaquias: "MAL",
  mateus: "MAT",
  marcos: "MRK",
  lucas: "LUK",
  john: "JHN",
  atos: "ACT",
  romanos: "ROM",
  galatas: "GAL",
  efesios: "EPH",
  filipenses: "PHP",
  colossenses: "COL",
  tessalonicenses: "1TH",
  timoteo: "1TI",
  filemom: "PHM",
  hebreus: "HEB",
  tiago: "JAS",
  pedro: "1PE",
  judas: "JUD",
  apocalipse: "REV",
  revelacao: "REV",
  revelacoes: "REV",

  // Formas com ordinal junto
  isamuel: "1SA",
  iisamuel: "2SA",
  isam: "1SA",
  iisam: "2SA",
  ireis: "1KI",
  iireis: "2KI",
  icronicas: "1CH",
  iicronicas: "2CH",
  icorintios: "1CO",
  iicorintios: "2CO",
  itessalonicenses: "1TH",
  iitessalonicenses: "2TH",
  itimoteo: "1TI",
  iitimoteo: "2TI",
  ipedro: "1PE",
  iipedro: "2PE",
  ijoao: "1JN",
  iijoao: "2JN",
  iiijoao: "3JN",

  // Abreviações populares
  gen: "GEN",
  gn: "GEN",
  ex: "EXO",
  lv: "LEV",
  nm: "NUM",
  dt: "DEU",
  js: "JOS",
  jz: "JDG",
  rt: "RUT",
  sm: "1SA",
  rs: "1KI",
  cr: "1CH",
  ed: "EZR",
  ne: "NEH",
  et: "EST",
  job: "JOB",
  sl: "PSA",
  pv: "PRO",
  ec: "ECC",
  ct: "SNG",
  is: "ISA",
  jr: "JER",
  lm: "LAM",
  ez: "EZK",
  dn: "DAN",
  os: "HOS",
  jl: "JOL",
  am: "AMO",
  ob: "OBA",
  jn: "JON",
  mq: "MIC",
  na: "NAM",
  hc: "HAB",
  sf: "ZEP",
  ag: "HAG",
  zc: "ZEC",
  ml: "MAL",
  mt: "MAT",
  mc: "MRK",
  lc: "LUK",
  joa: "JHN",
  at: "ACT",
  rm: "ROM",
  gl: "GAL",
  ef: "EPH",
  fp: "PHP",
  cl: "COL",
  ts: "1TH",
  tm: "1TI",
  tt: "TIT",
  fm: "PHM",
  hb: "HEB",
  tg: "JAS",
  pe: "1PE",
  jd: "JUD",
  ap: "REV",

  // Numerados sem separador
  "1sm": "1SA",
  "2sm": "2SA",
  "1rs": "1KI",
  "2rs": "2KI",
  "1cr": "1CH",
  "2cr": "2CH",
  "1co": "1CO",
  "2co": "2CO",
  "1ts": "1TH",
  "2ts": "2TH",
  "1tm": "1TI",
  "2tm": "2TI",
  "1pe": "1PE",
  "2pe": "2PE",
  "1jo": "1JN",
  "2jo": "2JN",
  "3jo": "3JN",
  "1cor": "1CO",
  "2cor": "2CO",
  "1corintios": "1CO",
  "2corintios": "2CO",
  "1tess": "1TH",
  "2tess": "2TH",
  "1tim": "1TI",
  "2tim": "2TI",
};

const generatedAliases = ALL_BOOKS.reduce<Record<string, string>>((accumulator, book) => {
  const base = [book.id, book.slug, book.abbrev, book.name];
  base.forEach((value) => {
    const normalized = normalizeAlias(String(value));
    if (normalized) accumulator[normalized] = book.id;
  });
  return accumulator;
}, {});

export const BOOK_ALIASES: Record<string, string> = {
  ...generatedAliases,
  ...Object.entries(manualAliases).reduce<Record<string, string>>((accumulator, [key, value]) => {
    accumulator[normalizeAlias(key)] = value;
    return accumulator;
  }, {}),
};

export const normalizeBookAlias = normalizeAlias;